{% set data = load_setup_py_data() %}

package:
  name: trnpy
  version: {{ data['version'] }}

source:
    path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  
  script: pip install .

  noarch: python

  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - trnpy = trnpy.trnpy_script:main

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - pandas >=1.2.1

    run:
        - python
        - pandas >=1.2.1
        - pyyaml >=5.1
        - psutil
        - openpyxl

    run_constrained:  # requirements of optional dependencies
        - bokeh <3.0

about:
    home: https://github.com/jnettels/trnpy
    summary: 'Parallelized TRNSYS simulation with Python'
    description: 'Parallelized TRNSYS simulation with Python'
    license: 'GPL3'
    license_file: LICENSE.txt
    author: 'Joris Zimmermann'
    author_email: 'joris.zimmermann@stw.de'