{% set data = load_setup_py_data() %}

package:
  name: trnpy
  version: {{ data['version'] }}

source:
    path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

  script: pip install .

  noarch: python

  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - trnpy = trnpy.trnpy_script:main

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - pandas >=2.0

    run:
        - python
        - pandas >=2.0
        - pyyaml >=5.1
        - psutil
        - openpyxl
        - xlsxwriter

    run_constrained:  # requirements of optional dependencies
        - bokeh <3.0  # Code not adapted to versions >=3.0 yet
        - selenium <4.3  # Required by bokeh<3.0, otherwise errors finding firefox

about:
    home: https://github.com/jnettels/trnpy
    summary: 'Parallelized TRNSYS simulation with Python'
    description: 'Parallelized TRNSYS simulation with Python'
    license: 'GPL3'
    license_file: LICENSE.txt
    author: 'Joris Zimmermann'
    author_email: 'joris.zimmermann@stw.de'